// Pure helpers for the field-app Customer Map screen. Everything here is plain
// TypeScript (no React, no react-native) so it can be unit-tested in a Node
// environment via vitest. The MapScreenImpl component composes these.
//
// Shared API filter contract for GET /customers/map (mirrored across the three
// changed UIs — native map, web map, and web nearby):
//   audience=customers|prospects|both
//   county=<case-insensitive text>
//   zip=<case-insensitive text>
//   minAcres=<nonnegative number>
//   maxAcres=<nonnegative number>
// `includeProspects` is kept as a backward-compatible fallback for old callers.
// When `audience` is omitted the API default stays customer-only, so the UIs
// always send an explicit audience (defaulting to "both").

export type Audience = "customers" | "prospects" | "both";

export const AUDIENCE_DEFAULT: Audience = "both";

/** Pin kinds rendered on the map. Mirrors CustomerMapPinKind in the API. */
export type MapPinKind = "customer" | "prospect";

/**
 * The subset of query params the map screen controls. Kept independent of the
 * (possibly stale) generated `ListCustomerMapPinsParams` so we can code against
 * the contract while the generated client is being regenerated by another
 * agent. `repId` comes from the existing All/Mine control.
 */
export type CustomerMapFilterInput = {
  audience: Audience;
  county: string;
  zip: string;
  minAcres: string;
  maxAcres: string;
  repId?: number;
};

/**
 * Raw text/number filter state as entered by the user. Distinct from
 * CustomerMapFilterInput so callers can hold user text (which may be blank or
 * partially typed) before it is normalised into request params.
 */
export type CustomerMapFilterState = {
  audience: Audience;
  county: string;
  zip: string;
  minAcres: string;
  maxAcres: string;
};

export const EMPTY_FILTER_STATE: CustomerMapFilterState = {
  audience: AUDIENCE_DEFAULT,
  county: "",
  zip: "",
  minAcres: "",
  maxAcres: "",
};

/** True when every field-app-controlled filter is at its default/empty value. */
export function isFilterStateDefault(state: CustomerMapFilterState): boolean {
  return (
    state.audience === AUDIENCE_DEFAULT &&
    state.county.trim() === "" &&
    state.zip.trim() === "" &&
    state.minAcres.trim() === "" &&
    state.maxAcres.trim() === ""
  );
}

/**
 * Parse a user-entered acreage string into a nonnegative number, or `undefined`
 * when blank/invalid/negative. Keeps the contract's "nonnegative number" rule
 * in one place so both the request params and the cache key agree.
 */
export function parseNonnegativeAcres(raw: string | null | undefined): number | undefined {
  if (raw == null) return undefined;
  const trimmed = String(raw).trim();
  if (trimmed === "") return undefined;
  const n = Number(trimmed);
  if (!Number.isFinite(n) || n < 0) return undefined;
  return n;
}

export function validateAcreageFilters(
  filters: Pick<CustomerMapFilterInput, "minAcres" | "maxAcres">,
): string | null {
  const minRaw = filters.minAcres.trim();
  const maxRaw = filters.maxAcres.trim();
  const minAcres = parseNonnegativeAcres(filters.minAcres);
  const maxAcres = parseNonnegativeAcres(filters.maxAcres);

  if (minRaw && minAcres === undefined) {
    return "Minimum acreage must be a non-negative number.";
  }
  if (maxRaw && maxAcres === undefined) {
    return "Maximum acreage must be a non-negative number.";
  }
  if (minAcres !== undefined && maxAcres !== undefined && minAcres > maxAcres) {
    return "Minimum acreage cannot be greater than maximum acreage.";
  }
  return null;
}

/**
 * Whether prospects may be shown at all. Non-sales roles never receive prospect
 * pins: even if a stale cache holds them, the UI must suppress them. Callers
 * pass the permission check result (`prospects.view`) plus any server-side
 * suppression signal.
 */
export function canShowProspects(opts: {
  hasProspectPermission: boolean;
  serverSuppressed?: boolean;
}): boolean {
  return opts.hasProspectPermission && !opts.serverSuppressed;
}

/**
 * The effective audience once permission/suppression is applied. When the user
 * asks for prospects (or both) but cannot see prospects, we downgrade to
 * customers so we never request or render prospect pins.
 */
export function effectiveAudience(requested: Audience, canProspects: boolean): Audience {
  if (canProspects) return requested;
  // No prospect access: anything involving prospects collapses to customers.
  return "customers";
}

/**
 * The audience toggle options a given user may pick. Non-sales roles only ever
 * see the customers option so they can neither request nor imagine prospects.
 */
export function audienceOptionsForUser(canProspects: boolean): Audience[] {
  if (canProspects) return ["both", "customers", "prospects"];
  return ["customers"];
}

/**
 * Build the request params for GET /customers/map from filter state. Sends an
 * explicit `audience` (contract) AND a matching `includeProspects` (fallback
 * for old callers / stale server), plus the normalised county/zip/acreage
 * filters and any repId. Blank/invalid filters are omitted entirely.
 */
export function buildMapPinsParams(
  input: CustomerMapFilterInput,
  canProspects: boolean,
): Record<string, string | number | boolean> {
  const audience = effectiveAudience(input.audience, canProspects);
  const params: Record<string, string | number | boolean> = {
    audience,
    // Backward-compatible fallback: old server reads includeProspects only.
    includeProspects: audience === "customers" ? false : true,
  };

  const county = input.county.trim();
  if (county) params.county = county;

  const zip = input.zip.trim();
  if (zip) params.zip = zip;

  const minAcres = parseNonnegativeAcres(input.minAcres);
  if (minAcres !== undefined) params.minAcres = minAcres;

  const maxAcres = parseNonnegativeAcres(input.maxAcres);
  if (maxAcres !== undefined) params.maxAcres = maxAcres;

  if (input.repId != null) params.repId = input.repId;

  return params;
}

/**
 * Stable, order-independent cache key for the offline store, derived from the
 * FULL filter/query state so filtered responses never overwrite each other.
 * Uses the normalised values (same normalisation as the request) and a sorted,
 * delimited encoding so equivalent states map to the same key regardless of
 * object key order.
 */
export function mapPinsCacheKey(
  input: CustomerMapFilterInput,
  canProspects: boolean,
): string {
  const params = buildMapPinsParams(input, canProspects);
  const parts = Object.keys(params)
    .sort()
    .map((k) => `${k}=${String(params[k])}`);
  return `customer-map-pins|${parts.join("&")}`;
}

// ---------------------------------------------------------------------------
// Client-side audience guard
// ---------------------------------------------------------------------------

type PinLike = { kind?: string | null };

/**
 * Client-side audience/permission guard applied to whatever the server or a
 * stale offline cache returns. Strips prospect pins for unauthorized users and
 * honours the currently-selected audience so a cached "both" response can't
 * leak prospects into a "customers" view (or to a non-sales role).
 */
export function filterPinsByAudience<T extends PinLike>(
  pins: T[],
  audience: Audience,
  canProspects: boolean,
): T[] {
  // Membership is decided against the *requested* audience so that asking for
  // "prospects" only never falls back to showing customers. Prospect pins are
  // additionally gated on permission so they can never leak to non-sales roles,
  // regardless of what the server or a stale cache returned.
  const wantsCustomers = audience === "both" || audience === "customers";
  const wantsProspects = audience === "both" || audience === "prospects";
  return pins.filter((p) => {
    const isProspect = p.kind === "prospect";
    if (isProspect) return canProspects && wantsProspects;
    return wantsCustomers;
  });
}

// ---------------------------------------------------------------------------
// Marker sizing
// ---------------------------------------------------------------------------

/**
 * Declared marker box (points). Both the customer circle and prospect star
 * must fit within this square regardless of acreage, so the
 * native marker's tracked size never changes and callout anchoring stays put.
 */
export const MARKER_BOX = 44;

/** Fixed glyph size (points) used when acreage-based sizing is turned off. */
export const FIXED_GLYPH = 26;

/** Smallest and largest rendered glyph size (points) within the marker box. */
export const MIN_GLYPH = 20;
export const MAX_GLYPH = 40;

/**
 * The acreage at (or above) which a glyph reaches MAX_GLYPH. Chosen so typical
 * field/prospect acreages spread meaningfully across the size range rather than
 * saturating immediately.
 */
export const ACRES_AT_MAX = 2000;

/**
 * Keep the prospect star conservatively inset so its white outline and shadow
 * remain comfortably inside the declared marker box.
 */
function ceilingFor(kind: MapPinKind): number {
  if (kind === "prospect") return Math.min(MAX_GLYPH, MARKER_BOX / Math.SQRT2);
  return MAX_GLYPH;
}

/**
 * Continuous acreage → glyph size (points), bounded to [MIN_GLYPH, ceiling].
 * Uses a sqrt curve so area — not linear diameter — grows roughly with acreage,
 * giving meaningful visual separation among small/medium farms without the
 * largest ones dwarfing the marker box. Null/invalid/zero acreage → MIN_GLYPH.
 */
export function acreageGlyphSize(
  totalAcres: number | null | undefined,
  kind: MapPinKind,
): number {
  const acres = totalAcres != null && Number.isFinite(totalAcres) && totalAcres > 0 ? totalAcres : 0;
  const t = Math.min(1, Math.sqrt(acres / ACRES_AT_MAX));
  const base = MIN_GLYPH + (MAX_GLYPH - MIN_GLYPH) * t;
  const size = Math.max(MIN_GLYPH, Math.min(ceilingFor(kind), base));
  // Round to a whole point so identical acreages produce identical sizes (and
  // thus stable marker keys / no stale sizes after tracksViewChanges settles).
  return Math.round(size);
}

/**
 * The size the marker glyph should render at. When `sizeByAcreage` is off,
 * every marker uses a single fixed size (still clamped to the kind's ceiling).
 * When on, it scales via `acreageGlyphSize`.
 */
export function markerGlyphSize(
  sizeByAcreage: boolean,
  totalAcres: number | null | undefined,
  kind: MapPinKind,
): number {
  if (!sizeByAcreage) {
    return Math.round(Math.min(FIXED_GLYPH, ceilingFor(kind)));
  }
  return acreageGlyphSize(totalAcres, kind);
}

/**
 * A stable string capturing everything that affects the marker's rendered
 * appearance/size. Embedding it in the marker `key` forces react-native-maps to
 * remount (and re-snapshot) the marker whenever its size/shape changes, so
 * `tracksViewChanges={false}` can't leave a stale bitmap behind.
 */
export function markerVisualKey(
  sizeByAcreage: boolean,
  totalAcres: number | null | undefined,
  kind: MapPinKind,
): string {
  return `${kind}:${sizeByAcreage ? "acre" : "fixed"}:${markerGlyphSize(sizeByAcreage, totalAcres, kind)}`;
}
